version: '3.4'

services:
  app:
    container_name: asp.net
    image: testapp2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - todo


  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "GoodPassword101"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - todo


networks:
  todo:
